import React, { useState, useEffect, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Plus, Upload, Trash2, QrCode, Download, Copy, Image, Loader2, Users, ChevronLeft, Pencil, RefreshCw } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { format } from 'date-fns';
import { zhTW } from 'date-fns/locale';

interface MessageCard {
  id: string;
  title: string;
  short_code: string;
  image_path: string;
  is_active: boolean;
  created_at: string;
}

interface Download {
  id: string;
  card_id: string;
  user_name: string;
  user_email: string;
  downloaded_at: string;
}

interface MessageCardManagerProps {
  onBack?: () => void;
}

export const MessageCardManager: React.FC<MessageCardManagerProps> = ({ onBack }) => {
  const [cards, setCards] = useState<MessageCard[]>([]);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [showEditDialog, setShowEditDialog] = useState(false);
  const [showQRDialog, setShowQRDialog] = useState(false);
  const [showDownloadsDialog, setShowDownloadsDialog] = useState(false);
  const [selectedCard, setSelectedCard] = useState<MessageCard | null>(null);
  const [downloads, setDownloads] = useState<Download[]>([]);
  const [downloadsLoading, setDownloadsLoading] = useState(false);
  
  // Create form state
  const [newTitle, setNewTitle] = useState('');
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  
  // Edit form state
  const [editTitle, setEditTitle] = useState('');
  const [editFile, setEditFile] = useState<File | null>(null);
  const [editPreviewUrl, setEditPreviewUrl] = useState<string | null>(null);
  const [updating, setUpdating] = useState(false);
  const editFileInputRef = useRef<HTMLInputElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    fetchCards();
  }, []);

  const fetchCards = async () => {
    try {
      const { data, error } = await supabase
        .from('message_cards')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setCards(data || []);
    } catch (err) {
      console.error('Error fetching cards:', err);
      toast.error('載入失敗');
    } finally {
      setLoading(false);
    }
  };

  const fetchDownloads = async (cardId: string) => {
    setDownloadsLoading(true);
    try {
      const { data, error } = await supabase
        .from('message_card_downloads')
        .select('*')
        .eq('card_id', cardId)
        .order('downloaded_at', { ascending: false });

      if (error) throw error;
      setDownloads(data || []);
    } catch (err) {
      console.error('Error fetching downloads:', err);
      toast.error('載入下載記錄失敗');
    } finally {
      setDownloadsLoading(false);
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate file type
    if (!file.type.startsWith('image/')) {
      toast.error('請選擇圖片檔案');
      return;
    }

    // Validate file size (max 10MB)
    if (file.size > 10 * 1024 * 1024) {
      toast.error('圖片大小不能超過 10MB');
      return;
    }

    setSelectedFile(file);
    setPreviewUrl(URL.createObjectURL(file));
  };

  const handleCreate = async () => {
    if (!newTitle.trim()) {
      toast.error('請輸入標題');
      return;
    }

    if (!selectedFile) {
      toast.error('請選擇圖片');
      return;
    }

    setUploading(true);
    try {
      // Upload image to storage
      const fileExt = selectedFile.name.split('.').pop();
      const fileName = `${Date.now()}_${Math.random().toString(36).substring(7)}.${fileExt}`;
      
      const { error: uploadError } = await supabase.storage
        .from('message-cards')
        .upload(fileName, selectedFile);

      if (uploadError) throw uploadError;

      // Create database record (short_code will be auto-generated by trigger)
      const { data, error: insertError } = await supabase
        .from('message_cards')
        .insert([{
          title: newTitle.trim(),
          image_path: fileName,
          short_code: '', // Will be overwritten by trigger
        }])
        .select()
        .single();

      if (insertError) throw insertError;

      toast.success('建立成功！');
      setCards(prev => [data, ...prev]);
      setShowCreateDialog(false);
      
      // Show QR code for new card
      setSelectedCard(data);
      setShowQRDialog(true);
      
      // Reset form
      setNewTitle('');
      setSelectedFile(null);
      setPreviewUrl(null);
    } catch (err) {
      console.error('Error creating card:', err);
      toast.error('建立失敗');
    } finally {
      setUploading(false);
    }
  };

  const handleDelete = async (card: MessageCard) => {
    try {
      // Delete from storage
      await supabase.storage.from('message-cards').remove([card.image_path]);
      
      // Delete from database
      const { error } = await supabase
        .from('message_cards')
        .delete()
        .eq('id', card.id);

      if (error) throw error;

      toast.success('已刪除');
      setCards(prev => prev.filter(c => c.id !== card.id));
    } catch (err) {
      console.error('Error deleting card:', err);
      toast.error('刪除失敗');
    }
  };

  const handleOpenEdit = (card: MessageCard) => {
    setSelectedCard(card);
    setEditTitle(card.title);
    setEditFile(null);
    setEditPreviewUrl(null);
    setShowEditDialog(true);
  };

  const handleEditFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      toast.error('請選擇圖片檔案');
      return;
    }

    if (file.size > 10 * 1024 * 1024) {
      toast.error('圖片大小不能超過 10MB');
      return;
    }

    setEditFile(file);
    setEditPreviewUrl(URL.createObjectURL(file));
  };

  const handleUpdate = async () => {
    if (!selectedCard) return;
    
    if (!editTitle.trim()) {
      toast.error('請輸入標題');
      return;
    }

    setUpdating(true);
    try {
      let newImagePath = selectedCard.image_path;

      // If new image selected, upload it
      if (editFile) {
        const fileExt = editFile.name.split('.').pop();
        const fileName = `${Date.now()}_${Math.random().toString(36).substring(7)}.${fileExt}`;
        
        const { error: uploadError } = await supabase.storage
          .from('message-cards')
          .upload(fileName, editFile);

        if (uploadError) throw uploadError;

        // Delete old image
        await supabase.storage.from('message-cards').remove([selectedCard.image_path]);
        
        newImagePath = fileName;
      }

      // Update database record
      const { data, error: updateError } = await supabase
        .from('message_cards')
        .update({
          title: editTitle.trim(),
          image_path: newImagePath,
        })
        .eq('id', selectedCard.id)
        .select()
        .single();

      if (updateError) throw updateError;

      toast.success('更新成功！');
      setCards(prev => prev.map(c => c.id === selectedCard.id ? data : c));
      setShowEditDialog(false);
      
      // Reset form
      setEditTitle('');
      setEditFile(null);
      setEditPreviewUrl(null);
    } catch (err) {
      console.error('Error updating card:', err);
      toast.error('更新失敗');
    } finally {
      setUpdating(false);
    }
  };

  const getDownloadUrl = (card: MessageCard) => {
    return `${window.location.origin}/card?code=${card.short_code}`;
  };

  const handleCopyLink = (card: MessageCard) => {
    navigator.clipboard.writeText(getDownloadUrl(card));
    toast.success('已複製連結');
  };

  const handleShowDownloads = (card: MessageCard) => {
    setSelectedCard(card);
    fetchDownloads(card.id);
    setShowDownloadsDialog(true);
  };

  const getImageUrl = (imagePath: string) => {
    const { data } = supabase.storage.from('message-cards').getPublicUrl(imagePath);
    return data.publicUrl;
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          {onBack && (
            <Button variant="ghost" size="icon" onClick={onBack}>
              <ChevronLeft className="w-5 h-5" />
            </Button>
          )}
          <div>
            <h2 className="text-xl sm:text-2xl font-semibold flex items-center gap-2">
              <Image className="w-5 h-5 sm:w-6 sm:h-6 text-secondary" />
              信息摘要卡片
            </h2>
            <p className="text-sm text-muted-foreground">管理與分享週報圖片</p>
          </div>
        </div>
        
        <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
          <DialogTrigger asChild>
            <Button variant="gold" className="gap-2">
              <Plus className="w-4 h-4" />
              新增卡片
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <DialogTitle>新增信息卡片</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="title">標題</Label>
                <Input
                  id="title"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="例如：2024/01/28 主日信息"
                />
              </div>

              <div className="space-y-2">
                <Label>圖片</Label>
                <input
                  type="file"
                  ref={fileInputRef}
                  className="hidden"
                  accept="image/*"
                  onChange={handleFileSelect}
                />
                {previewUrl ? (
                  <div className="space-y-2">
                    <div className="rounded-lg overflow-hidden bg-muted">
                      <img src={previewUrl} alt="Preview" className="w-full h-auto" />
                    </div>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => fileInputRef.current?.click()}
                    >
                      更換圖片
                    </Button>
                  </div>
                ) : (
                  <Button
                    variant="outline"
                    className="w-full h-32 border-dashed"
                    onClick={() => fileInputRef.current?.click()}
                  >
                    <div className="flex flex-col items-center gap-2">
                      <Upload className="w-8 h-8 text-muted-foreground" />
                      <span className="text-muted-foreground">點擊上傳圖片</span>
                    </div>
                  </Button>
                )}
              </div>

              <Button
                variant="gold"
                className="w-full"
                onClick={handleCreate}
                disabled={uploading || !newTitle.trim() || !selectedFile}
              >
                {uploading ? (
                  <><Loader2 className="w-4 h-4 mr-2 animate-spin" />上傳中...</>
                ) : (
                  '建立卡片'
                )}
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Cards List */}
      {cards.length === 0 ? (
        <Card className="border-dashed">
          <CardContent className="flex flex-col items-center justify-center py-12">
            <Image className="w-12 h-12 text-muted-foreground mb-4" />
            <p className="text-muted-foreground text-center">
              尚未建立任何信息卡片
            </p>
            <Button
              variant="outline"
              className="mt-4"
              onClick={() => setShowCreateDialog(true)}
            >
              <Plus className="w-4 h-4 mr-2" />
              新增第一張卡片
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {cards.map((card) => (
            <Card key={card.id} className="overflow-hidden">
              <div className="aspect-video bg-muted">
                <img
                  src={getImageUrl(card.image_path)}
                  alt={card.title}
                  className="w-full h-full object-cover"
                />
              </div>
              <CardHeader className="py-3 px-4">
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0 flex-1">
                    <CardTitle className="text-base truncate">{card.title}</CardTitle>
                    <CardDescription className="text-xs">
                      {format(new Date(card.created_at), 'yyyy/MM/dd HH:mm', { locale: zhTW })}
                    </CardDescription>
                  </div>
                  <Badge variant="secondary" className="font-mono text-sm">
                    {card.short_code}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="pt-0 px-4 pb-4">
                <div className="flex flex-wrap gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleOpenEdit(card)}
                  >
                    <Pencil className="w-4 h-4 mr-1" />
                    編輯
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      setSelectedCard(card);
                      setShowQRDialog(true);
                    }}
                  >
                    <QrCode className="w-4 h-4 mr-1" />
                    QR
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleCopyLink(card)}
                  >
                    <Copy className="w-4 h-4 mr-1" />
                    連結
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleShowDownloads(card)}
                  >
                    <Users className="w-4 h-4 mr-1" />
                    記錄
                  </Button>
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <Button variant="ghost" size="sm" className="text-destructive hover:text-destructive">
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <AlertDialogTitle>確定要刪除嗎？</AlertDialogTitle>
                        <AlertDialogDescription>
                          此操作無法復原，圖片和所有下載記錄將會被永久刪除。
                        </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                        <AlertDialogCancel>取消</AlertDialogCancel>
                        <AlertDialogAction
                          className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                          onClick={() => handleDelete(card)}
                        >
                          刪除
                        </AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* QR Code Dialog */}
      <Dialog open={showQRDialog} onOpenChange={setShowQRDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="text-center">{selectedCard?.title}</DialogTitle>
          </DialogHeader>
          {selectedCard && (
            <div className="flex flex-col items-center space-y-4">
              <div className="bg-white p-4 rounded-xl">
                <QRCodeSVG
                  value={getDownloadUrl(selectedCard)}
                  size={200}
                  level="H"
                />
              </div>
              
              <div className="text-center">
                <p className="text-sm text-muted-foreground mb-1">代碼</p>
                <p className="text-4xl font-mono font-bold tracking-widest text-primary">
                  {selectedCard.short_code}
                </p>
              </div>

              <div className="flex gap-2 w-full">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={() => handleCopyLink(selectedCard)}
                >
                  <Copy className="w-4 h-4 mr-2" />
                  複製連結
                </Button>
                <Button
                  variant="gold"
                  className="flex-1"
                  onClick={() => {
                    const svg = document.querySelector('#qr-download-svg');
                    if (svg) {
                      const svgData = new XMLSerializer().serializeToString(svg);
                      const canvas = document.createElement('canvas');
                      const ctx = canvas.getContext('2d');
                      const img = new window.Image();
                      img.onload = () => {
                        canvas.width = img.width;
                        canvas.height = img.height;
                        ctx?.drawImage(img, 0, 0);
                        const link = document.createElement('a');
                        link.download = `qr-${selectedCard.short_code}.png`;
                        link.href = canvas.toDataURL('image/png');
                        link.click();
                      };
                      img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
                    }
                  }}
                >
                  <Download className="w-4 h-4 mr-2" />
                  下載 QR
                </Button>
              </div>

              {/* Hidden SVG for download */}
              <div className="hidden">
                <QRCodeSVG
                  id="qr-download-svg"
                  value={getDownloadUrl(selectedCard)}
                  size={400}
                  level="H"
                />
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={showEditDialog} onOpenChange={setShowEditDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>編輯信息卡片</DialogTitle>
          </DialogHeader>
          {selectedCard && (
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="edit-title">標題</Label>
                <Input
                  id="edit-title"
                  value={editTitle}
                  onChange={(e) => setEditTitle(e.target.value)}
                  placeholder="例如：2024/01/28 主日信息"
                />
              </div>

              <div className="space-y-2">
                <Label>圖片</Label>
                <input
                  type="file"
                  ref={editFileInputRef}
                  className="hidden"
                  accept="image/*"
                  onChange={handleEditFileSelect}
                />
                <div className="space-y-2">
                  <div className="rounded-lg overflow-hidden bg-muted relative group">
                    <img 
                      src={editPreviewUrl || getImageUrl(selectedCard.image_path)} 
                      alt="Preview" 
                      className="w-full h-auto"
                    />
                    <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                      <Button
                        variant="secondary"
                        size="sm"
                        onClick={() => editFileInputRef.current?.click()}
                      >
                        <RefreshCw className="w-4 h-4 mr-2" />
                        更換圖片
                      </Button>
                    </div>
                  </div>
                  {editFile && (
                    <p className="text-xs text-muted-foreground">
                      已選擇新圖片：{editFile.name}
                    </p>
                  )}
                </div>
              </div>

              <div className="flex gap-2">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={() => setShowEditDialog(false)}
                >
                  取消
                </Button>
                <Button
                  variant="gold"
                  className="flex-1"
                  onClick={handleUpdate}
                  disabled={updating || !editTitle.trim()}
                >
                  {updating ? (
                    <><Loader2 className="w-4 h-4 mr-2 animate-spin" />更新中...</>
                  ) : (
                    '儲存變更'
                  )}
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Downloads Dialog */}
      <Dialog open={showDownloadsDialog} onOpenChange={setShowDownloadsDialog}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>下載記錄 - {selectedCard?.title}</DialogTitle>
          </DialogHeader>
          {downloadsLoading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="w-6 h-6 animate-spin" />
            </div>
          ) : downloads.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              尚無下載記錄
            </div>
          ) : (
            <div className="max-h-96 overflow-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>姓名</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>時間</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {downloads.map((d) => (
                    <TableRow key={d.id}>
                      <TableCell className="font-medium">{d.user_name}</TableCell>
                      <TableCell className="text-muted-foreground text-sm">
                        {d.user_email}
                      </TableCell>
                      <TableCell className="text-muted-foreground text-sm">
                        {format(new Date(d.downloaded_at), 'MM/dd HH:mm')}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
};
