import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/contexts/AuthContext';
import { useChurchContext } from '@/contexts/ChurchContext';
import { churchFetch } from '@/lib/churchFetch';
import { Button } from '@/components/ui/button';
export function PendingChurchAffiliations(){
 const church=useChurchContext();const {user,refreshAuth}=useAuth();const client=useQueryClient();
 const q=useQuery<{users:{id:string;displayName:string|null;email:string|null;church:null}[]}>({queryKey:['pending-church-affiliations',church?.identity],enabled:!!church?.data?.isSystemAdmin,retry:false,queryFn:async()=>{const r=await churchFetch('/api/admin/church-affiliations/pending');if(!r.ok)throw new Error('無法載入待核定會員，請重新確認管理權限。');return r.json();}});
 const update=useMutation({mutationFn:async(input:{id:string;name:string;church:string})=>{const r=await churchFetch(`/api/users/${input.id}/profile`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({church:input.church,expectedChurch:null})});if(!r.ok){if(r.status===409)await q.refetch();throw new Error(r.status===409?'會員歸屬已被其他管理者更新，請查看最新資料後再核定。':'核定尚未成功，請重新確認會員與教會。');}if(input.id===user?.id)await refreshAuth?.();},onSuccess:async()=>{await client.invalidateQueries({queryKey:['pending-church-affiliations']});await client.invalidateQueries({queryKey:['unified-members']});}});
 if(!church?.data?.isSystemAdmin)return null;
 return <details className="border-b py-3"><summary className="min-h-11 cursor-pointer font-semibold">待核定教會 · {q.data?.users.length??'…'}</summary><p className="my-2 text-sm text-muted-foreground">每位會員只能屬於一間教會。核定會影響教會分享牆、小家與課表權限，請先確認身分與所屬教會。</p>{q.isError&&<p role="alert">{q.error.message}<Button variant="outline" onClick={()=>void q.refetch()}>重新載入</Button></p>}{update.isError&&<p role="alert">{update.error.message}</p>}{q.data?.users.map(member=><div key={member.id} className="flex min-w-0 flex-wrap items-center gap-3 border-t py-3"><p className="min-w-0 flex-1 [overflow-wrap:anywhere]">{member.displayName||member.email||'未填姓名'}</p><label className="text-sm">核定教會<select aria-label={`核定 ${member.displayName||member.email||'未填姓名'} 的教會`} disabled={update.isPending} value="" className="ml-2 min-h-11 rounded-md border bg-background px-2" onChange={e=>{const id=e.target.value;const name=church.data?.allowedOptions.find(option=>option.id===id)?.name;if(name&&window.confirm(`確認將 ${member.displayName||member.email||'這位會員'} 核定為 ${name} 會員？`))update.mutate({id:member.id,name:member.displayName||member.email||'會員',church:id});}}><option value="">選擇並核定</option>{church.data?.allowedOptions.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></label></div>)}</details>;
}
