// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import FeedbackPage from './FeedbackPage';
const auth = vi.hoisted(() => ({ user: null as null | {id:string}, loading:false }));
vi.mock('@/contexts/AuthContext', () => ({useAuth:() => auth}));
vi.mock('@/components/layout/Header', () => ({Header:() => null}));
let client: QueryClient;
beforeEach(() => {auth.user=null;auth.loading=false;sessionStorage.clear();client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}});});
afterEach(() => {cleanup();client.clear();vi.restoreAllMocks();vi.unstubAllGlobals();});
function mount() {return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[{pathname:'/feedback',state:{from:'/learn/church-reading?secret=yes#token'}}]}><FeedbackPage /></MemoryRouter></QueryClientProvider>);}
function fill() {fireEvent.change(screen.getByLabelText('簡短標題'),{target:{value:'讀經無法繼續'}});fireEvent.change(screen.getByLabelText('內容與操作步驟'),{target:{value:'按下一天之後畫面沒有改變，請協助確認。'}});fireEvent.click(screen.getByRole('checkbox'));}
it('keeps an anonymous draft for login return and never sends it anonymously',() => {const fetch=vi.fn();vi.stubGlobal('fetch',fetch);mount();fill();expect(screen.getByRole('link',{name:'登入後繼續送出'})).toHaveAttribute('href','/login?returnTo=%2Ffeedback');expect(JSON.parse(sessionStorage.getItem('wechurch:feedback-draft:guest')!).title).toBe('讀經無法繼續');expect(fetch).not.toHaveBeenCalled();});
it('retries an uncertain send with the identical request ID and only a pathname',async () => {auth.user={id:'member-one'};let attempts=0;const fetch=vi.fn(async (_url:string,options?:RequestInit) => {if(options?.method==='POST'){attempts++;if(attempts===1)throw new Error('response lost');return {ok:true,json:async()=>({feedback:{id:'received'}})};}return {ok:true,json:async()=>({items:[]})};});vi.stubGlobal('fetch',fetch);mount();fill();fireEvent.click(screen.getByRole('button',{name:'送出意見'}));await screen.findByRole('alert');expect(screen.getByLabelText('簡短標題')).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'重新確認送出'}));await screen.findByText('已收到你的意見。可在下面查看處理進度。');const bodies=fetch.mock.calls.filter(([,o])=>o?.method==='POST').map(([,o])=>JSON.parse(o!.body as string));expect(bodies).toHaveLength(2);expect(bodies[0]).toEqual(bodies[1]);expect(bodies[0].location).toBe('/learn/church-reading');expect(bodies[0].requestId).toMatch(/^[a-f0-9-]{36}$/);await waitFor(()=>expect(sessionStorage.getItem('wechurch:feedback-draft:member-one')).toBeNull());});
it('restores the login draft into its owner key without exposing a different owner draft',() => {sessionStorage.setItem('wechurch:feedback-draft:other-member',JSON.stringify({category:'bug',title:'另一位的私人草稿',body:'不可交叉讀取這份草稿',urgency:'normal'}));sessionStorage.setItem('wechurch:feedback-draft:guest',JSON.stringify({category:'question',title:'未登入的問題',body:'登入後請保留這個問題',urgency:'normal',consent:true}));auth.user={id:'new-member'};vi.stubGlobal('fetch',vi.fn(async()=>({ok:true,json:async()=>({items:[]})})));mount();expect(screen.getByLabelText('簡短標題')).toHaveValue('未登入的問題');expect(sessionStorage.getItem('wechurch:feedback-draft:guest')).toBeNull();expect(sessionStorage.getItem('wechurch:feedback-draft:other-member')).not.toBeNull();});
it('works in memory when browser storage is unavailable',() => {vi.spyOn(Storage.prototype,'getItem').mockImplementation(()=>{throw new Error('blocked');});vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('blocked');});vi.spyOn(Storage.prototype,'removeItem').mockImplementation(()=>{throw new Error('blocked');});mount();fill();expect(screen.getByLabelText('簡短標題')).toHaveValue('讀經無法繼續');expect(screen.getByRole('link',{name:'登入後繼續送出'})).toBeVisible();});

it('uses Unicode code-point lengths and preserves a locked astral-character retry across reload',async()=>{auth.user={id:'member-one'};const requestId='689deffd-b736-41e3-ac85-9e573f199954';const body='🙏'.repeat(4000);const title='🌿'.repeat(110);sessionStorage.setItem('wechurch:feedback-draft:member-one',JSON.stringify({category:'bug',title,body,urgency:'normal',consent:true,location:'/feedback',requestId,locked:true}));const fetch=vi.fn(async(_url:string,o?:RequestInit)=>({ok:true,json:async()=>o?.method==='POST'?{feedback:{id:'received'}}:{items:[]}}));vi.stubGlobal('fetch',fetch);mount();expect(screen.getByLabelText('簡短標題')).toHaveValue(title);expect(screen.getByLabelText('內容與操作步驟')).toHaveValue(body);expect(screen.getByText('110 / 120 字，至少 3 字')).toBeVisible();expect(screen.getByText('4000 / 5000 字，至少 10 字')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'重新確認送出'}));await screen.findByText('已收到你的意見。可在下面查看處理進度。');const sent=JSON.parse(fetch.mock.calls.find(([,o])=>o?.method==='POST')![1]!.body as string);expect(sent).toMatchObject({requestId,title,body});});
it('counts emoji as one code point for the minimum and does not send over-limit input',()=>{auth.user={id:'member-one'};const fetch=vi.fn(async(_url:string,_options?:RequestInit)=>({ok:true,json:async()=>({items:[]})}));vi.stubGlobal('fetch',fetch);mount();fireEvent.change(screen.getByLabelText('簡短標題'),{target:{value:'🌿🌿'}});fireEvent.change(screen.getByLabelText('內容與操作步驟'),{target:{value:'🙏'.repeat(10)}});fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByRole('button',{name:'送出意見'})).toBeDisabled();fireEvent.change(screen.getByLabelText('簡短標題'),{target:{value:'🌿'.repeat(3)}});expect(screen.getByRole('button',{name:'送出意見'})).toBeEnabled();fireEvent.change(screen.getByLabelText('簡短標題'),{target:{value:'🌿'.repeat(121)}});expect(screen.getByRole('button',{name:'送出意見'})).toBeDisabled();expect(screen.getByLabelText('簡短標題')).toHaveValue('🌿'.repeat(121));expect(fetch.mock.calls.some(([,o])=>(o as RequestInit)?.method==='POST')).toBe(false);});

it('preserves both colliding drafts and never moves the owner draft into the guest slot',()=>{auth.user={id:'member-one'};const own={category:'bug',title:'帳號已有的草稿',body:'這是目前帳號的私人未完成內容',urgency:'normal',consent:true};const guest={...own,title:'登入前剛寫的草稿',body:'這是登入之前的新意見內容'};sessionStorage.setItem('wechurch:feedback-draft:member-one',JSON.stringify(own));sessionStorage.setItem('wechurch:feedback-draft:guest',JSON.stringify(guest));vi.stubGlobal('fetch',vi.fn(async()=>({ok:true,json:async()=>({items:[]})})));mount();expect(screen.getByLabelText('簡短標題')).toHaveValue(own.title);expect(JSON.parse(sessionStorage.getItem('wechurch:feedback-draft:guest')!).title).toBe(guest.title);fireEvent.click(screen.getByRole('button',{name:'接續這份草稿'}));expect(screen.getByLabelText('簡短標題')).toHaveValue(guest.title);expect(JSON.parse(sessionStorage.getItem('wechurch:feedback-draft:member-one:saved')!)[0]).toMatchObject(own);expect(sessionStorage.getItem('wechurch:feedback-draft:guest')).toBeNull();cleanup();auth.user={id:'member-two'};mount();expect(screen.getByLabelText('簡短標題')).toHaveValue('');expect(screen.queryByText(/帳號已有的草稿/)).toBeNull();});
it('refuses to switch away from an owner draft with an uncertain submitted request',()=>{auth.user={id:'member-one'};const own={category:'bug',title:'待確認送出原文',body:'不能丟棄這一份尚未確認送出的原文',urgency:'normal',consent:true,requestId:'689deffd-b736-41e3-ac85-9e573f199954',locked:true};const guest={...own,title:'匿名的新草稿',locked:false,requestId:undefined};sessionStorage.setItem('wechurch:feedback-draft:member-one',JSON.stringify(own));sessionStorage.setItem('wechurch:feedback-draft:guest',JSON.stringify(guest));vi.stubGlobal('fetch',vi.fn(async()=>({ok:true,json:async()=>({items:[]})})));mount();expect(screen.getByRole('button',{name:'接續這份草稿'})).toBeDisabled();expect(screen.getByLabelText('簡短標題')).toHaveValue(own.title);expect(JSON.parse(sessionStorage.getItem('wechurch:feedback-draft:guest')!).title).toBe(guest.title);});
it('shows confirmed rate limiting with a retry delay and preserves the request ID',async()=>{auth.user={id:'member-one'};vi.stubGlobal('fetch',vi.fn(async(_url:string,o?:RequestInit)=>({ok:o?.method!=='POST',status:429,text:async()=>'{"error":"請稍候"}',json:async()=>({items:[]})})));mount();fill();fireEvent.click(screen.getByRole('button',{name:'送出意見'}));await screen.findByRole('alert');expect(screen.getByRole('alert')).toHaveTextContent('送出次數較多');expect(screen.getByRole('alert')).not.toHaveTextContent('尚未確認送出結果');expect(screen.getByRole('button',{name:'請稍候 60 秒'})).toBeDisabled();const stored=JSON.parse(sessionStorage.getItem('wechurch:feedback-draft:member-one')!);expect(stored.requestId).toMatch(/^[a-f0-9-]{36}$/);expect(stored.locked).toBe(true);});

it('adopts the switched draft when only guest removal throws and never revives either sent draft',async()=>{auth.user={id:'member-one'};const owner={category:'bug',title:'帳號草稿原文',body:'這一份是帳號原本的未完成草稿內容',urgency:'normal',consent:true,location:'/feedback'};const guest={...owner,title:'登入前的新草稿',body:'這一份是登入前新增的另一份草稿內容'};sessionStorage.setItem('wechurch:feedback-draft:member-one',JSON.stringify(owner));sessionStorage.setItem('wechurch:feedback-draft:guest',JSON.stringify(guest));const remove=Storage.prototype.removeItem;vi.spyOn(Storage.prototype,'removeItem').mockImplementation(function(this:Storage,key:string){if(key==='wechurch:feedback-draft:guest')throw new Error('guest removal rejected');return remove.call(this,key);});const fetch=vi.fn(async(_url:string,o?:RequestInit)=>({ok:true,json:async()=>o?.method==='POST'?{feedback:{id:'received'}}:{items:[]}}));vi.stubGlobal('fetch',fetch);mount();fireEvent.click(screen.getByRole('button',{name:'接續這份草稿'}));expect(screen.getByLabelText('簡短標題')).toHaveValue(guest.title);expect(JSON.parse(sessionStorage.getItem('wechurch:feedback-draft:member-one')!).title).toBe(guest.title);expect(sessionStorage.getItem('wechurch:feedback-draft:guest')).toBe('');fireEvent.click(screen.getByRole('button',{name:'送出意見'}));await screen.findByText('已收到你的意見。可在下面查看處理進度。');expect(JSON.parse(sessionStorage.getItem('wechurch:feedback-draft:member-one:saved')!)).toMatchObject([owner]);cleanup();mount();expect(screen.getByLabelText('簡短標題')).toHaveValue('');expect(screen.queryByText(/登入前的新草稿/)).toBeNull();fireEvent.click(screen.getByRole('button',{name:'接續這份草稿'}));expect(screen.getByLabelText('簡短標題')).toHaveValue(owner.title);fireEvent.click(screen.getByRole('button',{name:'送出意見'}));await screen.findByText('已收到你的意見。可在下面查看處理進度。');await waitFor(()=>expect(JSON.parse(sessionStorage.getItem('wechurch:feedback-draft:member-one:saved')!)).toEqual([]));cleanup();mount();expect(screen.queryByRole('button',{name:'接續這份草稿'})).toBeNull();expect(screen.getByLabelText('簡短標題')).toHaveValue('');const posts=fetch.mock.calls.filter(([,o])=>o?.method==='POST').map(([,o])=>JSON.parse(o!.body as string));expect(posts).toHaveLength(2);expect(posts.map(row=>row.title)).toEqual([guest.title,owner.title]);});
