import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
type Client=(path:string,method?:string,body?:unknown)=>Promise<Response>;

// Only called by the existing disposable-loopback integrity runner, never a cloud operation.
export async function verifyCoLeadersHttp(pool:Pool,makeClient:()=>Client){
 const root='/api/life-groups';
 const actors:{id:string;client:Client}[]=[];
 for(const [i,role] of ['senior_pastor','member','member','member','member','member'].entries()){
  const client=makeClient(),email=`coleader-${randomUUID()}@example.test`;
  assert.equal((await client('/api/auth/register','POST',{email,password:randomUUID(),displayName:`合成雙領袖${i}`})).status,200);
  const id=(await pool.query('SELECT id FROM users WHERE email=$1',[email])).rows[0].id;
  await pool.query('UPDATE users SET church=$2 WHERE id=$1',[id,'IM 行動教會']);
  await pool.query('DELETE FROM user_roles WHERE user_id=$1',[id]);await pool.query('INSERT INTO user_roles(user_id,role) VALUES($1,$2)',[id,role]);actors.push({id,client});
 }
 const [director,first,second,replacement,other,last]=actors;
 const roleBefore=(await pool.query('SELECT user_id,role FROM user_roles WHERE user_id=ANY($1::uuid[]) ORDER BY user_id,role',[actors.map(a=>a.id)])).rows;
 const create=async(name:string,leaderUserId:string|null,coLeaderUserId:string|null)=>{const r=await director.client('/api/crm/groups','POST',{name,church:'IM 行動教會',leaderUserId,coLeaderUserId});assert.equal(r.status,201);return (await r.json()).id as string;};
 assert.equal((await director.client('/api/crm/groups','POST',{name:'不得重複',church:'IM 行動教會',leaderUserId:first.id,coLeaderUserId:first.id})).status,400);
 assert.equal((await director.client('/api/crm/groups','POST',{name:'無帳號不得授權',church:'IM 行動教會',coLeaderUserId:randomUUID()})).status,400);
 const id=await create('同權驗證-'+randomUUID(),first.id,second.id),foreign=await create('跨家驗證-'+randomUUID(),other.id,null),empty=await create('未指派驗證-'+randomUUID(),null,null);
 await assert.rejects(pool.query('UPDATE small_groups SET co_leader_user_id=leader_user_id WHERE id=$1',[id]),(error:{code?:string})=>error.code==='23514');
 await assert.rejects(pool.query('UPDATE small_groups SET co_leader_user_id=$2 WHERE id=$1',[id,randomUUID()]),(error:{code?:string})=>error.code==='23503');
 const appointments=await (await director.client('/api/access-control')).json();assert.equal(appointments.appointments.find((g:{id:string})=>g.id===id).coLeaderId,second.id);
 assert.equal(appointments.appointmentSummary.activeGroupCount,appointments.appointments.length);
 await pool.query('UPDATE users SET church=$2 WHERE id=$1',[other.id,'火樂']);
 const invalidAppointment=await (await director.client('/api/access-control')).json();
 assert.equal(invalidAppointment.appointments.find((g:{id:string})=>g.id===foreign).leaderId,null);
 assert.equal(invalidAppointment.appointmentSummary.invalidLeaderSlotCount,appointments.appointmentSummary.invalidLeaderSlotCount+1);
 assert.equal(invalidAppointment.appointmentSummary.assignedLeaderCount,appointments.appointmentSummary.assignedLeaderCount-1);
 assert.deepEqual((await (await other.client('/api/access-control/me')).json()).appointments,[]);
 await pool.query('UPDATE users SET church=$2 WHERE id=$1',[other.id,'IM 行動教會']);
 const devotionResponse=await director.client('/api/admin/church-devotions','POST',{date:'2026-10-05',planName:'雙人合成讀經',dayNumber:1,scriptureReference:'詩篇 1',scriptureText:'',devotionalTitle:'合成驗收',devotionalText:'只用於隔離測試',prayer:'',loveAction:'',status:'published'});assert.equal(devotionResponse.status,201);const devotion=await devotionResponse.json();
 const membershipBefore=(await pool.query('SELECT count(*)::int AS count FROM small_group_members WHERE group_id=$1',[id])).rows[0].count;assert.equal(membershipBefore,0);
 const info=async(client:Client,g=id)=>{const r=await client(`${root}/${g}`);assert.equal(r.status,200);return r.json();};
 for(const actor of [first,second]){
  const g=await info(actor.client);assert.equal(g.manager,true);assert.equal(g.leaderId,first.id);assert.equal(g.coLeaderId,second.id);assert(g.leaderName&&g.coLeaderName);assert.equal(g.members.filter((m:{manager:boolean})=>m.manager).length,2);
  assert.equal((await actor.client(`${root}/${foreign}`)).status,404);
  assert.equal((await actor.client(`${root}/management/${foreign}`)).status,403);
  assert.equal((await actor.client(`${root}/dashboard?scope=${foreign}`)).status,404);
  assert.equal((await actor.client(`${root}/dashboard/${id}/roster?date=2026-10-05`)).status,200);
  assert.equal((await actor.client(`${root}/${id}/invite`,'POST')).status,200);
  assert.equal((await actor.client(`${root}/${id}/members/${actor.id}`,'DELETE')).status,409);
  assert.equal((await actor.client(`${root}/management/${id}/move`,'POST',{userId:actor.id,targetGroupId:null,reason:'必須先交接'})).status,409);
  const mine=await (await actor.client(root)).json();assert.equal(mine.groups.find((g:{id:string})=>g.id===id).memberCount,2);
  assert(!mine.groups.some((g:{id:string})=>g.id===foreign||g.id===empty));
  const myAccess=await (await actor.client('/api/access-control/me')).json();
  assert.equal(myAccess.canEnterCrm,true);assert.equal(myAccess.canEnterAdmin,true);assert.equal(myAccess.canManageGroups,true);
  assert.deepEqual(myAccess.appointments,[{groupId:id,groupName:g.name,role:'group_leader'}]);
  assert.deepEqual(myAccess.permissions,[]);assert.deepEqual(myAccess.grants,[]);
  const crm=await actor.client('/api/crm/groups');assert.equal(crm.status,200);
  const crmGroups=await crm.json();assert.deepEqual(crmGroups.map((row:{id:string})=>row.id),[id]);
  assert.equal(crmGroups[0].memberCount,2);assert.equal(crmGroups[0].unlinkedMemberCount,0);
  const crmAccess=await (await actor.client('/api/crm/access')).json();assert.equal(crmAccess.canEnterCrm,true);
  assert.equal(crmAccess.canAssignScopes,false);assert.equal(crmAccess.canViewPersonal,false);assert.equal(crmAccess.canManageMembers,false);assert.equal(crmAccess.canManageCare,true);
  assert.deepEqual(crmAccess.scope.groups,[id]);assert.deepEqual(crmAccess.scope.churches,[]);
  assert.equal((await actor.client('/api/crm/groups','POST',{name:'不得自行開新小家',church:'IM 行動教會'})).status,403);
  assert.equal((await actor.client('/api/access-control')).status,403);
  const crmMembers=await (await actor.client('/api/users')).json();
  assert.deepEqual(crmMembers.map((row:{id:string})=>row.id).sort(),[first.id,second.id].sort());
  assert(crmMembers.every((row:{ministryRoles:string[]})=>row.ministryRoles.includes('小家長')));
  assert(!crmMembers.some((row:{id:string})=>row.id===other.id));
  assert(crmMembers.every((row:Record<string,unknown>)=>!Object.hasOwn(row,'email')));
  assert.equal((await actor.client(`${root}/${id}/reading/${devotion.id}`,'PUT',{version:devotion.version,done:true})).status,200);
  assert.equal((await actor.client(`${root}/${foreign}/reading?date=2026-10-05`)).status,404);
  const mentorTargets=await (await actor.client('/api/mentoring/targets')).json();assert(mentorTargets.some((t:{groupId:string;mentorId:string})=>t.groupId===id&&t.mentorId===(actor.id===first.id?second.id:first.id)));assert(!mentorTargets.some((t:{groupId:string})=>t.groupId===foreign));
  const targets=await (await actor.client('/api/support/targets')).json();assert(targets.some((t:{id:string;receiverId:string})=>t.id===id&&t.receiverId===(actor.id===first.id?second.id:first.id)));
 }
 const readers=await (await second.client(`${root}/${id}/reading?date=2026-10-05`)).json();assert.deepEqual(readers.readers.map((r:{id:string})=>r.id).sort(),[first.id,second.id].sort());
 const postId=randomUUID();assert.equal((await first.client(`${root}/${id}/shares/${postId}`,'PUT',{kind:'message',title:'舊內容',body:'任命時可見的合成內容',consent:true})).status,200);
 assert.equal((await second.client(`${root}/${id}/shares/${postId}`)).status,200);
 assert.equal((await other.client(`${root}/${id}/shares/${postId}`)).status,404);
 const participantComment=randomUUID(),reply=randomUUID();
 assert.equal((await second.client(`${root}/${id}/shares/${postId}/comments/${participantComment}`,'PUT',{body:'參與合成對話'})).status,200);
 assert.equal((await first.client(`${root}/${id}/shares/${postId}/comments/${reply}`,'PUT',{body:'合成回覆'})).status,200);
 assert((await (await second.client('/api/notifications')).json()).items.some((n:{href:string})=>n.href.includes(reply)));
 const person=(await pool.query("INSERT INTO persons(display_name) VALUES('雙人陪伴合成') RETURNING id")).rows[0].id;
 const template=(await pool.query("SELECT id FROM journey_templates WHERE slug='love-journey-28'")).rows[0].id;
 const journey=(await pool.query('INSERT INTO person_journeys(person_id,template_id,owner_user_id) VALUES($1,$2,$3) RETURNING id',[person,template,first.id])).rows[0].id;
 const contract=randomUUID();assert.equal((await first.client(`/api/mentoring/contracts/${contract}`,'PUT',{journeyId:journey,groupId:id,mentorId:second.id,cadenceDays:14,agreement:'合成彼此同意',consent:true})).status,200);
 assert.equal((await second.client(`/api/mentoring/contracts/${contract}`,'PATCH',{version:1,action:'accept',consent:true})).status,200);
 assert.equal((await second.client(`/api/mentoring/contracts/${contract}`)).status,200);assert.equal((await other.client(`/api/mentoring/contracts/${contract}`)).status,404);
 const settings=async(extra:Record<string,unknown>={})=>{const groups=await (await director.client(root+'/management')).json();const g=groups.groups.find((v:{id:string})=>v.id===id);return {version:g.version,name:g.name,description:g.description,meeting:g.meeting,announcement:g.announcement,listed:g.listed,status:g.status,leaderId:g.leaderId,coLeaderId:g.coLeaderId,...extra};};
 const patch=async(extra:Record<string,unknown>)=>director.client(`${root}/management/${id}`,'PATCH',await settings(extra));
 const concurrent=await settings({announcement:'互斥版本合成'});
 const race=await Promise.all([director.client(`${root}/management/${id}`,'PATCH',concurrent),director.client(`${root}/management/${id}`,'PATCH',concurrent)]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);
 await pool.query('INSERT INTO small_group_members(group_id,user_id) VALUES($1,$2)',[id,last.id]);
 await pool.query('UPDATE users SET church=$2 WHERE id=$1',[last.id,'火樂']);
 const currentRoster=await (await first.client('/api/users')).json();assert(!currentRoster.some((row:{id:string})=>row.id===last.id));
 assert.equal((await patch({coLeaderId:last.id})).status,400);
 await pool.query('DELETE FROM small_group_members WHERE group_id=$1 AND user_id=$2',[id,last.id]);await pool.query('UPDATE users SET church=$2 WHERE id=$1',[last.id,'IM 行動教會']);
 assert.equal((await patch({coLeaderId:other.id})).status,400);assert.equal((await patch({coLeaderId:randomUUID()})).status,400);
 const effective=await settings({leaderId:second.id});delete effective.coLeaderId;
 assert.equal((await director.client(`${root}/management/${id}`,'PATCH',effective)).status,400);assert.equal((await info(first.client)).coLeaderId,second.id);
 assert.equal((await second.client(`${root}/management/${id}`,'PATCH',await settings({coLeaderId:replacement.id}))).status,403);
 assert.equal((await patch({coLeaderId:replacement.id})).status,400);
 assert.equal((await replacement.client(`${root}/directory/${id}/join`,'POST',{})).status,200);
 assert.equal((await second.client(`${root}/${id}/requests/${replacement.id}`,'POST',{approve:true})).status,200);
 const replacementMembership=(await pool.query('SELECT md5(row_to_json(m)::text) AS digest FROM small_group_members m WHERE group_id=$1 AND user_id=$2 AND is_active',[id,replacement.id])).rows;
 const oldInvite=await (await second.client(`${root}/${id}/invite`,'POST')).json();
 assert.equal((await patch({coLeaderId:replacement.id})).status,200);
 assert.equal((await last.client(`${root}/join`,'POST',{token:oldInvite.token})).status,404);
 assert.equal((await info(second.client)).manager,false);
 const revokedAccess=await (await second.client('/api/access-control/me')).json();assert.deepEqual(revokedAccess.appointments,[]);assert.equal(revokedAccess.canEnterCrm,false);assert.equal(revokedAccess.canEnterAdmin,false);
 assert.equal((await second.client('/api/crm/groups')).status,403);
 const afterHandoffMembers=await (await director.client('/api/users')).json();assert(!afterHandoffMembers.find((row:{id:string})=>row.id===second.id).ministryRoles.includes('小家長'));
 assert.equal((await second.client(`/api/mentoring/contracts/${contract}`)).status,404);
 assert(!(await (await second.client('/api/notifications')).json()).items.some((n:{href:string})=>n.href.includes(reply)));assert.equal((await info(replacement.client)).manager,true);
 assert.equal((await second.client(`${root}/${id}/shares/${postId}`)).status,404);
 assert.equal((await second.client(`${root}/${id}/invite`,'POST')).status,404);
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM small_group_members WHERE group_id=$1 AND user_id=$2 AND is_active',[id,second.id])).rows[0].count,1);
 const legacy=await settings({meeting:'省略co仍保留'});delete legacy.coLeaderId;assert.equal((await director.client(`${root}/management/${id}`,'PATCH',legacy)).status,200);assert.equal((await info(first.client)).coLeaderId,replacement.id);
 assert.equal((await patch({leaderId:replacement.id,coLeaderId:first.id})).status,200);
 assert.equal((await info(first.client)).manager,true);assert.equal((await info(replacement.client)).manager,true);
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM small_group_members WHERE group_id=$1 AND user_id=$2 AND is_active',[id,first.id])).rows[0].count,0);
 assert.equal((await patch({leaderId:null})).status,200);assert.equal((await info(first.client)).manager,true);assert.equal((await info(replacement.client)).manager,false);
 assert.deepEqual((await pool.query('SELECT md5(row_to_json(m)::text) AS digest FROM small_group_members m WHERE group_id=$1 AND user_id=$2 AND is_active',[id,replacement.id])).rows,replacementMembership);
 assert.equal((await patch({coLeaderId:null})).status,200);assert.equal((await info(first.client)).manager,false);
 assert.equal((await patch({status:'archived'})).status,409);
 const lifecycleGroup=await create('封存雙人-'+randomUUID(),other.id,last.id);
 await pool.query('INSERT INTO small_group_members(group_id,user_id) VALUES($1,$2),($1,$3)',[lifecycleGroup,other.id,last.id]);
 const lifecycleSettings=async(status:string)=>{const rows=await (await director.client(root+'/management')).json();const g=rows.groups.find((v:{id:string})=>v.id===lifecycleGroup);return {version:g.version,name:g.name,description:g.description,meeting:g.meeting,announcement:g.announcement,listed:g.listed,status,leaderId:g.leaderId,coLeaderId:g.coLeaderId};};
 const lifecycleInvite=await (await last.client(`${root}/${lifecycleGroup}/invite`,'POST')).json();
 assert.equal((await director.client(`${root}/management/${lifecycleGroup}`,'PATCH',await lifecycleSettings('paused'))).status,200);
 assert((await (await last.client('/api/access-control/me')).json()).appointments.some((g:{groupId:string})=>g.groupId===lifecycleGroup));
 assert.equal((await (await last.client('/api/crm/groups')).json()).find((g:{id:string})=>g.id===lifecycleGroup).memberCount,2);
 assert.equal((await (await director.client(root+'/management')).json()).groups.find((g:{id:string})=>g.id===lifecycleGroup).memberCount,2);
 assert.equal((await director.client(`${root}/management/${lifecycleGroup}`,'PATCH',await lifecycleSettings('archived'))).status,200);
 assert(!(await (await last.client('/api/access-control/me')).json()).appointments.some((g:{groupId:string})=>g.groupId===lifecycleGroup));
 assert.equal((await last.client(`${root}/management/${lifecycleGroup}`,'PATCH',await lifecycleSettings('active'))).status,403);
 assert.equal((await director.client(`${root}/management/${lifecycleGroup}`,'PATCH',await lifecycleSettings('active'))).status,200);
 assert.equal((await first.client(`${root}/join`,'POST',{token:lifecycleInvite.token})).status,404);
 const rollbackBefore=(await pool.query('SELECT md5(row_to_json(g)::text) AS digest FROM small_groups g WHERE id=$1',[lifecycleGroup])).rows;
 assert.equal((await director.client(`${root}/management/${lifecycleGroup}`,'PATCH',{...await lifecycleSettings('archived'),coLeaderId:null})).status,409);
 assert.deepEqual((await pool.query('SELECT md5(row_to_json(g)::text) AS digest FROM small_groups g WHERE id=$1',[lifecycleGroup])).rows,rollbackBefore);
 const event=(await pool.query("SELECT count(*)::int AS count FROM family_membership_events WHERE group_id=$1 AND action='leaders_changed'",[id])).rows[0].count;assert(event>=4);
 const roleAfter=(await pool.query('SELECT user_id,role FROM user_roles WHERE user_id=ANY($1::uuid[]) ORDER BY user_id,role',[actors.map(a=>a.id)])).rows;assert.deepEqual(roleAfter,roleBefore);
 console.log('PASS co-leaders parity, reading, support, mentoring, notifications, IDOR, cross-church, FK/distinct, version race, effective pair, handoff, invite revocation, history preservation/boundary, lifecycle rollback and role preservation');
}
