import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
type Client = (path: string, method?: string, body?: unknown) => Promise<Response>;

export async function verifyFamilyHttp(pool: Pool, makeClient: () => Client) {
  const origin = '/api/life-groups';
  const actors: { client: Client; id: string }[] = [];
  for (const [role, church] of [['senior_pastor','IM 行動教會'], ['member','IM 行動教會'], ['senior_pastor','火樂'], ['future_leader','IM 行動教會']]) {
    const client = makeClient(), email = `family-${randomUUID()}@example.test`;
    assert.equal((await client('/api/auth/register','POST',{ email, password: randomUUID(), displayName: '小家驗證' })).status,200);
    const id = (await pool.query('SELECT id FROM users WHERE email=$1',[email])).rows[0].id;
    await pool.query('UPDATE users SET church=$2 WHERE id=$1',[id,church]);
    await pool.query('DELETE FROM user_roles WHERE user_id=$1',[id]);
    await pool.query('INSERT INTO user_roles(user_id,role) VALUES($1,$2)',[id,role]);
    actors.push({ client,id });
  }
  const [leader,member,outsider,future] = actors;
  const create = async (name: string) => {
    const r = await leader.client(origin+'/management','POST',{name,church:'IM 行動教會'}); assert.equal(r.status,201); return (await r.json()).id as string;
  };
  const first = await create('驗證小家一'), second = await create('驗證小家二');
  const settings = { version:1, name:'驗證小家一', description:'公開簡介', meeting:'週五晚上', announcement:'私人聚會地址', listed:true, status:'active', leaderId:leader.id };
  assert.equal((await leader.client(`${origin}/management/${first}`,'PATCH',settings)).status,200);
  assert.equal((await member.client(`${origin}/management/${first}`,'PATCH',{...settings,version:2})).status,403);
  assert.equal((await outsider.client(`${origin}/management/${first}`)).status,403);
  assert.equal((await future.client(origin+'/management','POST',{name:'越權',church:'IM 行動教會'})).status,403);
  const directory = await (await member.client(origin+'/directory?church='+encodeURIComponent('IM 行動教會'))).json();
  assert(directory.groups.some((g: {id:string})=>g.id===first));
  assert(!directory.groups.some((g: {id:string})=>g.id===second));
  assert(!JSON.stringify(directory).includes('私人聚會地址'));
  assert.equal((await member.client(`${origin}/directory/${second}/join`,'POST',{})).status,404);
  assert.equal((await member.client(`${origin}/directory/${first}/join`,'POST',{})).status,200);
  assert.equal((await member.client(`${origin}/${first}/shares?kind=all`)).status,404);
  const historicalId = randomUUID();
  assert.equal((await leader.client(`${origin}/${first}/shares/${historicalId}`,'PUT',{kind:'prayer',title:'舊代禱',body:'加入前的私密內容',consent:true})).status,200);
  const matching = { church:'IM 行動教會', availability:'週五', region:'線上', contact:'fixture@example.test', consent:true };
  assert.equal((await member.client(origin+'/matching','POST',matching)).status,201);
  assert.equal((await member.client(origin+'/matching','POST',matching)).status,201);
  const ownRequests = await (await member.client(origin+'/matching')).json(); assert.equal(ownRequests.length,1);
  const intakeId = ownRequests[0].id;
  assert.equal((await outsider.client(`${origin}/management/matching/${intakeId}`,'PATCH',{version:1,status:'contacting'})).status,403);
  assert.equal((await outsider.client(origin+'/management')).status,200);
  assert(!(await (await outsider.client(origin+'/management')).json()).requests.some((r: {id:string})=>r.id===intakeId));
  assert.equal((await leader.client(`${origin}/management/matching/${intakeId}`,'PATCH',{version:1,status:'contacting',message:'已聯繫'})).status,200);
  assert.equal((await leader.client(`${origin}/management/matching/${intakeId}`,'PATCH',{version:1,status:'matched',groupId:first})).status,409);
  assert.equal((await leader.client(`${origin}/management/matching/${intakeId}`,'PATCH',{version:2,status:'matched',groupId:first})).status,200);
  assert.equal((await member.client(`${origin}/${first}`)).status,404);
  assert.equal((await leader.client(`${origin}/management/${first}/requests/${member.id}`,'POST',{approve:true})).status,200);
  assert.equal((await member.client(`${origin}/${first}`)).status,200);
  const feed = await (await member.client(`${origin}/${first}/shares?kind=all`)).json();
  assert(!feed.some((p: {id:string})=>p.id===historicalId));
  assert.equal((await member.client(`${origin}/${first}/shares/${historicalId}/comments`)).status,404);
  const postId = randomUUID(), post = {kind:'message',title:'平安',body:'本週聚會見',consent:true};
  assert.equal((await member.client(`${origin}/${first}/shares/${postId}`,'PUT',post)).status,200);
  assert.equal((await member.client(`${origin}/${first}/shares/${postId}`,'PUT',post)).status,200);
  assert.equal((await leader.client(`${origin}/${first}/shares/${postId}/comments/${randomUUID()}`,'PUT',{body:'歡迎你'})).status,200);
  assert.equal((await member.client(`${origin}/${first}/shares?kind=all`)).status,200);
  assert.equal((await outsider.client(`${origin}/${first}/shares?kind=all`)).status,404);
  const invite = await (await leader.client(`${origin}/${second}/invite`,'POST',{})).json();
  assert.match(invite.code,/^[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}$/);
  assert.equal((await future.client(origin+'/join','POST',{token:invite.code})).status,200);
  assert.equal((await future.client(`${origin}/${second}`)).status,404);
  await leader.client(`${origin}/${second}/invite`,'POST',{});
  assert.equal((await future.client(origin+'/join','POST',{token:invite.token})).status,404);
  assert.equal((await leader.client(`${origin}/management/${first}/move`,'POST',{userId:leader.id,targetGroupId:second,reason:'驗證'})).status,409);
  assert.equal((await outsider.client(`${origin}/management/${first}/move`,'POST',{userId:member.id,targetGroupId:second,reason:'越權'})).status,403);
  assert.equal((await leader.client(`${origin}/management/${first}/move`,'POST',{userId:member.id,targetGroupId:second,reason:'測試轉家'})).status,200);
  assert.equal((await member.client(`${origin}/${first}/shares?kind=all`)).status,404);
  assert.equal((await member.client(`${origin}/${second}`)).status,200);
  assert(!(await (await member.client(`${origin}/${second}/shares?kind=all`)).json()).some((p: {id:string})=>p.id===postId));
  assert.equal((await leader.client(`${origin}/management/${second}/move`,'POST',{userId:member.id,targetGroupId:null,reason:'測試退出'})).status,200);
  assert.equal((await member.client(`${origin}/${second}`)).status,404);
  assert.equal((await pool.query('SELECT id FROM users WHERE id=$1',[member.id])).rowCount,1);
  const events = await pool.query('SELECT action FROM family_membership_events WHERE user_id=$1',[member.id]);
  assert(events.rows.some(e=>e.action==='transferred_out'));
  assert.equal((await leader.client(`${origin}/management/${first}`,'PATCH',{...settings,version:2,status:'archived'})).status,200);
  assert.equal((await leader.client(`${origin}/${first}`)).status,404);
  console.log('PASS families: directory privacy, intake deduplication/scope/versioning, join approval, history privacy, message/reply, short invite rotation, atomic transfer, exit and archive');
}
