import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
type Client = (path: string, method?: string, body?: unknown) => Promise<Response>;
export async function verifyCareHttp(pool: Pool, makeClient: () => Client) {
  const clients = [makeClient(), makeClient(), makeClient(), makeClient()], ids: string[] = [];
  for (const c of clients) {
    const email = `care-${randomUUID()}@example.test`;
    assert.equal((await c('/api/auth/register', 'POST', { email, password: randomUUID(), displayName: 'Care fixture' })).status, 200);
    ids.push((await pool.query('SELECT id FROM users WHERE email=$1', [email])).rows[0].id);
  }
  const [owner, pastor, foreign, member] = clients;
  await pool.query("UPDATE users SET church='IM 行動教會' WHERE id=ANY($1::uuid[])", [ids]);
  await pool.query("UPDATE users SET church='火樂' WHERE id=$1", [ids[2]]);
  await pool.query("INSERT INTO user_roles(user_id,role) VALUES($1,'pastor'),($2,'minister') ON CONFLICT DO NOTHING", [ids[1], ids[2]]);
  const guest = makeClient();
  assert.equal((await guest('/api/care/contacts')).status, 401);
  assert.equal((await guest('/api/care-visits/summary')).status, 401);
  assert.equal((await owner('/api/care/contacts', 'POST', { name: 'Test', nextCareDate: '2026-02-30' })).status, 400);
  const created = await owner('/api/care/contacts', 'POST', { name: 'Care test', need: 'PRIVATE_NEED', prayer: 'PRIVATE_PRAYER', nextCareDate: '2026-09-29' });
  assert.equal(created.status, 201); const contact = await created.json();
  const action = { id: randomUUID(), actionType: 'call', note: 'PRIVATE_HISTORY', nextCareDate: '2026-10-01', nextAction: 'Call again' };
  assert.equal((await owner(`/api/care/contacts/${contact.id}/actions`, 'POST', action)).status, 201);
  assert.equal((await owner(`/api/care/contacts/${contact.id}/actions`, 'POST', action)).status, 201);
  assert.equal((await pool.query('SELECT count(*)::int n FROM care_actions WHERE contact_id=$1', [contact.id])).rows[0].n, 1);
  assert.equal((await member(`/api/care/contacts/${contact.id}/actions`)).status, 404);
  assert.equal((await pastor(`/api/care/contacts/${contact.id}/actions`)).status, 404);
  assert.equal((await member(`/api/care/contacts/${contact.id}`, 'PATCH', { name: 'attack' })).status, 404);
  let contacts = await (await owner('/api/care/contacts')).json();
  assert.equal(contacts[0].nextCareDate, '2026-10-01'); assert(contacts[0].lastCaredAt);
  assert.equal((await owner(`/api/care/contacts/${contact.id}`, 'DELETE')).status, 200);
  assert.equal((await (await owner('/api/care/contacts')).json()).length, 0);
  assert.equal((await owner(`/api/care/contacts/${contact.id}/actions`, 'POST', { actionType: 'note' })).status, 404);
  contacts = await (await owner('/api/care/contacts?includeArchived=1')).json(); assert.equal(contacts[0].isArchived, true);
  assert.equal((await owner(`/api/care/contacts/${contact.id}`, 'PATCH', { isArchived: false })).status, 200);
  assert.equal((await (await owner(`/api/care/contacts/${contact.id}/actions`)).json()).actions[0].note, 'PRIVATE_HISTORY');

  const input = { contactId: contact.id, name: '需要探訪的朋友', reason: 'ONLY_SHARED_REASON', contactMethod: '請聯絡提出者', urgency: 'urgent', consent: true };
  const normalId = randomUUID(), id = randomUUID();
  assert.equal((await owner('/api/care-visits/' + id, 'PUT', { ...input, consent: false })).status, 400);
  assert.equal((await member('/api/care-visits/' + id, 'PUT', input)).status, 404);
  assert.equal((await owner('/api/care-visits/' + normalId, 'PUT', { ...input, urgency: 'normal' })).status, 200);
  assert.equal((await owner('/api/care-visits/' + id, 'PUT', input)).status, 200);
  assert.equal((await owner('/api/care-visits/' + id, 'PUT', input)).status, 200);
  assert.equal((await pool.query('SELECT count(*)::int n FROM care_visit_requests WHERE id=$1', [id])).rows[0].n, 1);
  assert.equal((await member('/api/care-visits?mode=inbox')).status, 403);
  assert.equal((await member(`/api/care-visits/${id}/events`)).status, 404);
  assert.equal((await foreign(`/api/care-visits/${id}/events`)).status, 404);
  assert.equal((await (await foreign('/api/care-visits?mode=inbox')).json()).requests.length, 0);
  const inbox = await (await pastor('/api/care-visits?mode=inbox')).json();
  assert.equal(inbox.requests[0].id, id); assert(!JSON.stringify(inbox).includes('PRIVATE_'));
  const summary = await (await pastor('/api/care-visits/summary')).json(); assert.equal(summary.pending, 2); assert.equal(summary.urgent, 1);
  const update = { version: 1, status: 'assigned', assigneeId: ids[1], dueDate: '2026-10-02', note: 'Will call tomorrow' };
  assert.equal((await owner('/api/care-visits/' + id, 'PATCH', update)).status, 403);
  assert.equal((await pastor('/api/care-visits/' + id, 'PATCH', { ...update, assigneeId: ids[2] })).status, 400);
  assert.equal((await pastor('/api/care-visits/' + id, 'PATCH', { ...update, assigneeId: ids[3] })).status, 400);
  const results = await Promise.all([pastor('/api/care-visits/' + id, 'PATCH', update), pastor('/api/care-visits/' + id, 'PATCH', update)]);
  assert.deepEqual(results.map(r => r.status).sort(), [200, 409]);
  const own = (await (await owner('/api/care-visits')).json()).requests.find((r: { id: string }) => r.id === id);
  assert.equal(own.status, 'assigned'); assert.equal(own.dueDate, '2026-10-02');
  assert.equal((await owner('/api/care-visits/' + id, 'PATCH', { ...update, version: 2, status: 'cancelled', note: 'No longer needed' })).status, 200);
  assert.equal((await pastor('/api/care-visits/' + id, 'PATCH', { ...update, version: 3, status: 'completed' })).status, 409);
  assert.equal((await pastor('/api/care-visits/' + normalId, 'PATCH', { ...update, status: 'completed' })).status, 200);
  assert.equal((await (await pastor('/api/care-visits/summary')).json()).pending, 0);
  assert((await (await owner(`/api/care-visits/${id}/events`)).json()).events.length >= 3);
  const reassigned = randomUUID();
  assert.equal((await owner('/api/care-visits/' + reassigned, 'PUT', input)).status, 200);
  assert.equal((await pastor('/api/care-visits/' + reassigned, 'PATCH', update)).status, 200);
  await pool.query("DELETE FROM user_roles WHERE user_id=$1 AND role='pastor'", [ids[1]]);
  assert.equal((await owner('/api/care-visits/' + reassigned, 'PATCH', { ...update, version: 2, status: 'cancelled', note: 'Cancel after pastoral staff change' })).status, 200);
  assert.equal((await pastor(`/api/care-visits/${id}/events`)).status, 404);
  assert.equal((await (await owner('/api/care-visits/summary')).json()).available, false);
  console.log('PASS care: recurring follow-up, archive/restore, private history, consent, team church scope, urgent ordering, idempotency, concurrent assignment, cancellation and role revocation');
}
