// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
const auth = vi.hoisted(() => ({user:null as null | {id:string},loading:false}));
vi.mock('@/contexts/AuthContext',()=>({useAuth:()=>auth}));
beforeEach(()=>{auth.user=null;auth.loading=false;localStorage.clear();vi.resetModules();});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
async function mount(path='/') { const mod=await import('./IntroductionTour');render(<MemoryRouter initialEntries={[path]}><mod.IntroductionTour /></MemoryRouter>);return {...mod,...await import('@/lib/introduction')}; }
it('explains login to a first-time visitor and persists skip',async()=>{await mount();expect(screen.getByRole('dialog')).toBeVisible();expect(screen.getByRole('link',{name:'登入後繼續'})).toHaveAttribute('href','/login?returnTo=%2Fhelp');fireEvent.click(screen.getByRole('button',{name:'略過導覽'}));expect(screen.queryByRole('dialog')).toBeNull();expect(localStorage.getItem('wechurch:introduction:v1:guest')).toBe('done');});
it('does not interrupt auth loading, deep links, or an existing completion',async()=>{auth.loading=true;await mount();expect(screen.queryByRole('dialog')).toBeNull();cleanup();auth.loading=false;await mount('/?invitation=abc');expect(screen.queryByRole('dialog')).toBeNull();cleanup();localStorage.setItem('wechurch:introduction:v1:guest','done');await mount();expect(screen.queryByRole('dialog')).toBeNull();});
it('offers the completed introduction again from help and uses logged-in copy',async()=>{localStorage.setItem('wechurch:introduction:v1:member','done');auth.user={id:'member'};const mod=await mount('/help');expect(screen.queryByRole('dialog')).toBeNull();fireEvent(window,new Event('wechurch:open-introduction'));expect(await screen.findByRole('dialog')).toBeVisible();expect(screen.getByText('歡迎回來，一起看看 WeChurch')).toBeVisible();expect(screen.queryByRole('link',{name:'登入後繼續'})).toBeNull();for(let i=0;i<mod.guideSteps.length-1;i++)fireEvent.click(screen.getByRole('button',{name:'下一步'}));expect(screen.getByRole('link',{name:'前往意見反饋'})).toHaveAttribute('href','/feedback');fireEvent.click(screen.getByRole('button',{name:'開始使用'}));expect(screen.queryByRole('dialog')).toBeNull();});
it('dismisses and can reopen when storage access throws',async()=>{vi.spyOn(Storage.prototype,'getItem').mockImplementation(()=>{throw new Error('storage disabled');});vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('storage disabled');});await mount();fireEvent.click(screen.getByRole('button',{name:'略過導覽'}));expect(screen.queryByRole('dialog')).toBeNull();fireEvent(window,new Event('wechurch:open-introduction'));expect(await screen.findByRole('dialog')).toBeVisible();fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();});

it('starts the first signed-in account introduction after a guest skipped it',async()=>{await mount();fireEvent.click(screen.getByRole('button',{name:'略過導覽'}));cleanup();auth.user={id:'member-one'};await mount();expect(screen.getByRole('dialog')).toBeVisible();expect(screen.getByText('歡迎回來，一起看看 WeChurch')).toBeVisible();expect(localStorage.getItem('wechurch:introduction:v1:guest')).toBe('done');expect(localStorage.getItem('wechurch:introduction:v1:member-one')).toBeNull();});
it('keeps introduction completion separate for accounts sharing a device',async()=>{auth.user={id:'member-one'};const mod=await mount();for(let i=0;i<mod.guideSteps.length-1;i++)fireEvent.click(screen.getByRole('button',{name:'下一步'}));fireEvent.click(screen.getByRole('button',{name:'開始使用'}));expect(localStorage.getItem('wechurch:introduction:v1:member-one')).toBe('done');cleanup();auth.user={id:'member-two'};await mount();expect(screen.getByRole('dialog')).toBeVisible();expect(localStorage.getItem('wechurch:introduction:v1:member-two')).toBeNull();cleanup();auth.user={id:'member-one'};await mount();expect(screen.queryByRole('dialog')).toBeNull();});
